### PR TITLE
Avoid Mono compilation

### PR DESCRIPTION
**Pull request by zapov**
Put generated source among other sources (for simplicity sake)

If somebody wants to change the model, it needs to uncomment annotation processor, delete the generated java file and compile the project.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Should this also include source files generated, or are they already included?

**Comment by cowtowncoder** [comment]
Actually assuming it's fine to merge, easy to undo or add files if need be.

**Comment by zapov** [comment]
Yes, the ExternalSerialization.java is the generated file.
I just copied it manually from target into src

**Comment by cowtowncoder** [comment]
Oh actually it was included; just missed it as contents were not included. Thanks!

**Pull request merged**
